// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PigBot.Database;

namespace PigBot.Migrations
{
    [DbContext(typeof(PigbotDbContext))]
    partial class PigbotDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028");

            modelBuilder.Entity("PigBot.Database.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<ulong>("UserId");

                    b.HasKey("Id");

                    b.ToTable("AdminUsers");
                });

            modelBuilder.Entity("PigBot.Database.BlackList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<ulong>("UserId");

                    b.HasKey("Id");

                    b.ToTable("BlackLists");
                });

            modelBuilder.Entity("PigBot.Database.CommandPolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Allowed");

                    b.Property<string>("CommandName");

                    b.Property<ulong>("GuildId");

                    b.HasKey("Id");

                    b.ToTable("CommandPolicies");
                });

            modelBuilder.Entity("PigBot.Database.CoolDownPolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CommandName");

                    b.Property<int>("CooldownSeconds");

                    b.Property<ulong>("GuildId");

                    b.Property<DateTime>("LastExecution");

                    b.HasKey("Id");

                    b.ToTable("CoolDownPolicies");
                });

            modelBuilder.Entity("PigBot.Database.FourchanPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<string>("DateTime");

                    b.Property<string>("FileUrl");

                    b.Property<int>("PostId");

                    b.HasKey("Id");

                    b.ToTable("FourchanPosts");
                });
#pragma warning restore 612, 618
        }
    }
}
